export enum CorporateType {
  LIMITED_LIABILITY = 'LIMITED_LIABILITY',
  SOLE_TRADER = 'SOLE_TRADER',
  PARTNERSHIP = 'PARTNERSHIP',
  PUBLIC_LIMITED_COMPANY = 'PUBLIC_LIMITED_COMPANY',
  JOINT_STOCK_COMPANY = 'JOINT_STOCK_COMPANY',
  CHARITY = 'CHARITY',
  DECENTRALISED_AUTONOMOUS_ORGANISATION = 'DECENTRALISED_AUTONOMOUS_ORGANISATION',
}
